version: '3'
services:
  postgresql:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
